CREATE TABLE IF NOT EXISTS "HIS_Patient" (
    "PatientID" INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1) PRIMARY KEY,
    "RegistrationDate" TIMESTAMP NOT NULL,
    "FirstName" VARCHAR(150) NOT NULL,
    "MiddleName" VARCHAR(150) NOT NULL,
    "LastName" VARCHAR(150) NOT NULL,
    "Gender" INT NOT NULL,
    "DateofBirth" TIMESTAMP NOT NULL,
    "NationalityID" VARCHAR(3) NOT NULL,
    "FirstVisit" TIMESTAMP NOT NULL,
    "LastVisit" TIMESTAMP NOT NULL,
    "NoOfVisit" INT NOT NULL,
    "MobileNumber" VARCHAR(10) NOT NULL,
    "EmailAddress" VARCHAR(150),
    "IsPregnant" INT,
    "BloodGroup" INT,
    "RHFactor" VARCHAR(10),
    "RegisteredDoctor" INT,
    "EmergencyContactName" VARCHAR(150),
    "EmergencyContactNo" VARCHAR(10)
);


CREATE TABLE "HIS_Appointment" (
    "AppointmentNo" INT NOT NULL,
    "AppointmentDate" TIMESTAMP,
    "PatientID" INT REFERENCES "HIS_Patient"("PatientID") NOT NULL,
    "ClinicID" INT NOT NULL,
    "DoctorID" INT NOT NULL,
    "StartTime" TIMESTAMP NOT NULL,
    "EndTime" TIMESTAMP NOT NULL,
    "VisitType" INT NOT NULL,
    "VisitFor" INT NOT NULL,
    "Notes" TEXT,
    "IsVirtual" INT
);

CREATE TABLE "HIS_DoctorOrder" (
    "PatientID" INT REFERENCES "HIS_Patient"("PatientID") NOT NULL,
    "ActualOrderDate" DATE NOT NULL,
    "ActualOrderTime" TIME,
    "OrderNotes" TEXT,
    "NursingNotes" TEXT
);


CREATE TABLE "HIS_PatientVitalSigns" (
    "PatientID" INT REFERENCES "HIS_Patient"("PatientID") NOT NULL,
    "WeightKg" FLOAT,
    "HeightCm" FLOAT,
    "BodyMassIndex" FLOAT,
    "TemperatureCelcius" FLOAT,
    "PulseBeatPerMinute" INT,
    "RespirationBeatPerMinute" INT,
    "BloodPressureLower" INT,
    "BloodPressureHigher" INT,
    "SAO2" INT,
    "FIO2" FLOAT,
    "PainScore" FLOAT,
    "PainLocation" VARCHAR(40),
    "PainDuration" VARCHAR(40),
    "PainCharacter" VARCHAR(40),
    "PainFrequency" VARCHAR(40),
    "TriageCategory" INT,
    "GCScore" FLOAT,
    "CreatedOn" TIMESTAMP
);